import { WatchEntry } from '@/types/watch';

export const INITIAL_WATCH_LIST: WatchEntry[] = [
  {
    id: 'sample-w1',
    tmdbId: 157336,
    title: 'Interstellar',
    originalTitle: 'Interstellar',
    mediaType: 'MOVIE',
    posterImage: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropImage: 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    status: 'COMPLETED',
    rating: 10,
    runtimeMinutes: 169,
    platform: 'Bioskop (IMAX) & Laptop',
    releaseYear: '2014',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    review: 'Masterpiece karya Christopher Nolan. Musik dari Hans Zimmer dan visual black hole Gargantua memberikan pengalaman emosional yang tak terlupakan.',
    notes: `### Catatan Pribadi:
- Penjelasan dilatasi waktu di planet Miller (1 jam = 7 tahun bumi) sangat dramatis.
- Konsep gravitasi sebagai penghubung dimensi waktu melalui tesseract.`,
    startDate: '2022-08-15',
    finishDate: '2022-08-15',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'sample-w2',
    tmdbId: 209867,
    title: 'Frieren: Beyond Journey\'s End',
    originalTitle: '葬送のフリーレン',
    mediaType: 'ANIME',
    posterImage: 'https://image.tmdb.org/t/p/w500/dqzenchTd7lp5zht7BdlqM7RBhD.jpg',
    backdropImage: 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    status: 'COMPLETED',
    rating: 10,
    currentEpisode: 28,
    totalEpisodes: 28,
    currentSeason: 1,
    totalSeasons: 1,
    runtimeMinutes: 24,
    platform: 'Bstation / YouTube Muse',
    releaseYear: '2023',
    genres: ['Animation', 'Fantasy', 'Adventure'],
    review: 'Anime fantasi dengan ritme cerita yang tenang tapi menyentuh hati. Koreografi animasi pertarungan sihir di ujian First-Class Mage sangat luar biasa.',
    notes: `### Catatan Karakter:
- **Frieren:** Elf penyihir yang baru menyadari arti kebersamaan setelah Himmel meninggal.
- **Fern & Stark:** Dinamika hubungan murid yang sangat hangat.`,
    startDate: '2023-10-05',
    finishDate: '2024-03-24',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'sample-w3',
    tmdbId: 211075,
    title: 'Solo Leveling',
    originalTitle: '俺だけレベルアップな件',
    mediaType: 'ANIME',
    posterImage: 'https://image.tmdb.org/t/p/w500/geCRueV3ElhRTr0xtJuClJ7xtIj.jpg',
    backdropImage: 'https://image.tmdb.org/t/p/original/gJL5idqDjh789Y6879R3f0QkG2E.jpg',
    status: 'WATCHING',
    rating: 9,
    currentEpisode: 9,
    totalEpisodes: 12,
    currentSeason: 1,
    totalSeasons: 1,
    runtimeMinutes: 24,
    platform: 'Netflix',
    releaseYear: '2024',
    genres: ['Animation', 'Action & Adventure', 'Fantasy'],
    review: 'Adaptasi manhwa yang sangat dinanti. Adegan kebangkitan bayangan Igris benar-benar keren!',
    notes: 'Terakhir nonton episode 9 saat Jinwoo menyelesaikan Job Change Quest di Red Gate.',
    startDate: '2024-02-10',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'sample-w4',
    tmdbId: 206586,
    title: 'Queen of Tears',
    originalTitle: '눈물의 여왕',
    mediaType: 'SERIES',
    posterImage: 'https://image.tmdb.org/t/p/w500/t0p714FjRvh7rMv5mZ19nKkQW0r.jpg',
    backdropImage: 'https://image.tmdb.org/t/p/original/2wT8Y7uQf6vD0e7q3u5F4bB8w1e.jpg',
    status: 'COMPLETED',
    rating: 9,
    currentEpisode: 16,
    totalEpisodes: 16,
    currentSeason: 1,
    totalSeasons: 1,
    runtimeMinutes: 75,
    platform: 'Netflix / TV',
    releaseYear: '2024',
    genres: ['Drama', 'Romance'],
    review: 'Akting Kim Soo-hyun dan Kim Ji-won sangat solid. Plot twist dan emosi di setiap episode dieksekusi dengan baik.',
    startDate: '2024-03-10',
    finishDate: '2024-04-29',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'sample-w5',
    tmdbId: 693134,
    title: 'Dune: Part Two',
    originalTitle: 'Dune: Part Two',
    mediaType: 'MOVIE',
    posterImage: 'https://image.tmdb.org/t/p/w500/czembW0Rk1Ke7lCJGahbOhdCuhV.jpg',
    backdropImage: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    status: 'PLAN_TO_WATCH',
    rating: 0,
    runtimeMinutes: 166,
    platform: 'Bioskop XXI / Laptop',
    releaseYear: '2024',
    genres: ['Sci-Fi', 'Adventure'],
    review: 'Rencana ditonton akhir pekan untuk melihat kelanjutan perang Arrakis.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
